{{- if or .Values.blink.postgres.url .Values.blink.auth.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blink.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blink.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.blink.postgres.url }}
  postgres-url: {{ .Values.blink.postgres.url | quote }}
  {{- end }}
  {{- if .Values.blink.auth.secret }}
  auth-secret: {{ .Values.blink.auth.secret | quote }}
  {{- end }}
{{- end }}
