{{- if .Values.blink.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blink.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blink.labels" . | nindent 4 }}
    {{- with .Values.blink.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.blink.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
