dist:
  name: collector
  output_path: ./dist

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/namedpipereceiver v0.143.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.143.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.143.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.143.0
